package wizeline.crypto.currency.utils

const val BASE_URL = "https://api.bitso.com/v3/"

val NAME_CURRENCY = mapOf(
    "btc" to "Bitcoin",
    "eth" to "Ethereum",
    "xrp" to "XRP",
    "ltc" to "Litecoin",
    "bch" to "Bitcoin Cash",
    "tusd" to "TrueUSD",
    "mana" to "Decentraland",
    "bat" to "Basic Attention Token",
    "dai" to "Dai",
    "usd" to "USD",
    "matic" to "Polygon",
    "shib" to "Shiba Inu",
    "usdt" to "Tether",
    "chz" to "Chiliz",
    "doge" to "Dogecoin",
    "sol" to "Solana",
    "ada" to "Cardano",
    "comp" to "Compound",
    "link" to "Chainlink",
    "uni" to "Uniswap",
    "aave" to "Aave",
    "axs" to "Axie Infinity",
    "dydx" to "dYdX",
    "yfi" to "yearn.finance",
    "sand" to "The Sandbox",
    "snx" to "Synthetix",
    "mkr" to "Maker",
    "enj" to "Enjin Coin",
    "ftm" to "Fantom",
    "crv" to "Curve DAO Token",
    "gala" to "Gala",
    "lrc" to "Loopring",
    "grt" to "The Graph",
    "ape" to "ApeCoin",
    "sushi" to "SushiSwap",
    "omg" to "OMG Network",
    "dot" to "Polkadot",
    "qnt" to "Quant",
    "bal" to "Balancer",
    "trx" to "TRON",
    "algo" to "Algorand",
    "ldo" to "Lido DAO",
    "xlm" to "Stellar",
    "paxg" to "PAX Gold",
    "brl" to "Real brasileño",
    "mxn" to "Pesos MX",
    "ars" to "Peso Argentino",
    "cop" to "Peso Colombiano"

)