package com.example.myapplication.repository

import com.example.myapplication.data.model.SimpleBook

class BitsoProvider {

    companion object{
        val bitsoFirst = listOf<SimpleBook>(
            SimpleBook(
                "btc_mxn",
                "2.0E7",
                "40000"
            ),
            SimpleBook(
                "eth_btc",
                "1.0",
                "0.003"
            ),
            SimpleBook(
                "xrp_btc",
                "3.0E-4",
                "8.0E-7"
            ),
            SimpleBook(
                "xrp_mxn",
                "300.0",
                "1.0E-5"
            ),
            SimpleBook(
                "ltc_btc",
                "0.06",
                "1.0E-4"
            ),
            SimpleBook(
                "ltc_mxn",
                "50000.0",
                "100.0"
            ),
            SimpleBook(
                "bch_btc",
                "0.2",
                "4.0E-4"
            ),
            SimpleBook(
                "bch_mxn",
                "100000.0",
                "300.0"
            ),
            SimpleBook(
                "tusd_btc",
                "5.0E-4",
                "1.0E-6"
            ),
            SimpleBook(
                "tusd_mxn",
                "400.0",
                "1.0"
            ),
            SimpleBook(
                "mana_btc",
                "0.001",
                "3.0E-6"
            ),
            SimpleBook(
                "btc_mxn",
                "2.0E7",
                "40000"
            ),
            SimpleBook(
                "eth_btc",
                "1.0",
                "0.003"
            ),
            SimpleBook(
                "xrp_btc",
                "3.0E-4",
                "8.0E-7"
            ),
            SimpleBook(
                "xrp_mxn",
                "300.0",
                "1.0E-5"
            ),
            SimpleBook(
                "ltc_btc",
                "0.06",
                "1.0E-4"
            ),
            SimpleBook(
                "ltc_mxn",
                "50000.0",
                "100.0"
            ),
            SimpleBook(
                "bch_btc",
                "0.2",
                "4.0E-4"
            ),
            SimpleBook(
                "bch_mxn",
                "100000.0",
                "300.0"
            ),
            SimpleBook(
                "tusd_btc",
                "5.0E-4",
                "1.0E-6"
            ),
            SimpleBook(
                "tusd_mxn",
                "400.0",
                "1.0"
            ),
            SimpleBook(
                "mana_btc",
                "0.001",
                "3.0E-6"
            ),
            SimpleBook(
                "btc_mxn",
                "2.0E7",
                "40000"
            ),
            SimpleBook(
                "eth_btc",
                "1.0",
                "0.003"
            ),
            SimpleBook(
                "xrp_btc",
                "3.0E-4",
                "8.0E-7"
            ),
            SimpleBook(
                "xrp_mxn",
                "300.0",
                "1.0E-5"
            ),
            SimpleBook(
                "ltc_btc",
                "0.06",
                "1.0E-4"
            ),
            SimpleBook(
                "ltc_mxn",
                "50000.0",
                "100.0"
            ),
            SimpleBook(
                "bch_btc",
                "0.2",
                "4.0E-4"
            ),
            SimpleBook(
                "bch_mxn",
                "100000.0",
                "300.0"
            ),
            SimpleBook(
                "tusd_btc",
                "5.0E-4",
                "1.0E-6"
            ),
            SimpleBook(
                "tusd_mxn",
                "400.0",
                "1.0"
            ),
            SimpleBook(
                "mana_btc",
                "0.001",
                "3.0E-6"
            ),
        )
    }
}